=== Security

In version Genie 3.x there existed a
https://github.com/Netflix/genie/tree/3.3.x/genie-web/src/main/java/com/netflix/genie/web/security[security module]
built on top of https://projects.spring.io/spring-security/[Spring Security]. This module contained a lot of
custom code to make security work in the Netflix security environment at the time. It attempted to abstract this into
reusable components but still was pretty specific.

https://medium.com/netflix-techblog/netflix-oss-and-spring-boot-coming-full-circle-4855947713a0[Spring at Netflix] has
evolved since that time into the primary Java runtime platform. As part of this process our core runtime teams have
produced security modules built on Spring Security which provide paved path integration with Netflix security
security mechanism. Genie has been using this paved path since the 4.x line has started releasing candidates. As such
we've made the decision to remove the `genie-security` module as it is a burden to support and likely isn't very
useful out of the box for most use cases. The recommendation if security is desired is to take the `genie-web` project
and build it into your own project in conjunction with some Spring Security implementations that work for your
environment. This is how we ship Genie internally. If you want to reference how this might look have a look
at the https://github.com/Netflix/genie/tree/v4.0.0-rc.31/genie-security[4.0.0-rc.31] code which is the last candidate
release to contain our old `genie-security` code.
