name: Spark Shell
user: genieDemo
description: Spark Shell Command
status: ACTIVE
setupFile: http://genie-apache/commands/spark/2.2.3/setupShell.sh
configs: []
executable: ${SPARK_HOME}/bin/spark-shell
version: 2.2.3
tags:
  - type:spark-shell
  - ver:2.2.3
  - ver:2.2
checkDelay: 5000
clusterCriteria:
  - tags:
      - type:yarn
