name: Spark Shell
user: genieDemo
description: Spark Shell Command
status: ACTIVE
setupFile: http://genie-apache/commands/spark/2.4.6/setupShell.sh
configs: []
executable: ${SPARK_HOME}/bin/spark-shell
version: 2.4.6
tags:
  - type:spark-shell
  - ver:2.4.6
  - ver:2.4
checkDelay: 5000
clusterCriteria:
  - tags:
      - type:yarn
