grpc:
  server:
    port: 0

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
      - io.awspring.cloud.autoconfigure.s3.S3TransferManagerAutoConfiguration
