version: "2"
services:
  genie:
    image: netflixoss/genie-app:${GENIE_VERSION}
    ports:
      - "8080:8080"
    depends_on:
      - genie-hadoop-prod
      - genie-hadoop-test
      - genie-apache
    tty: true
    container_name: genie_demo_app_${GENIE_VERSION}
  genie-apache:
    image: netflixoss/genie-demo-apache:${GENIE_VERSION}
    tty: true
    container_name: genie_demo_apache_${GENIE_VERSION}
  genie-client:
    image: netflixoss/genie-demo-client:${GENIE_VERSION}
    depends_on:
      - genie
    tty: true
    container_name: genie_demo_client_${GENIE_VERSION}
  genie-hadoop-prod:
    image: sequenceiq/hadoop-docker:2.7.1
    command: /bin/bash -c "/usr/local/hadoop/sbin/mr-jobhistory-daemon.sh start historyserver && /etc/bootstrap.sh -bash"
    ports:
      - "19888:19888"
      - "50070:50070"
      - "50075:50075"
      - "8088:8088"
    tty: true
    container_name: genie_demo_hadoop_prod_${GENIE_VERSION}
  genie-hadoop-test:
    image: sequenceiq/hadoop-docker:2.7.1
    command: /bin/bash -c "/usr/local/hadoop/sbin/mr-jobhistory-daemon.sh start historyserver && /etc/bootstrap.sh -bash"
    ports:
      - "19889:19888"
      - "50071:50070"
      - "50076:50075"
      - "8089:8088"
    tty: true
    container_name: genie_demo_hadoop_test_${GENIE_VERSION}
