##
#
#  Copyright 2016 Netflix, Inc.
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#
##

banner:
  location: genie-banner.txt

eureka:
  client:
    enabled: false

genie:
  file:
    cache:
      location: file:///tmp/genie/cache
  health:
    maxCpuLoadPercent: 80
  jobs:
    cleanup:
      deleteArchiveFile: true
      deleteDependencies: true
    forwarding:
      enabled: true
      port: 8080
      scheme: http
    locations:
      archives: file:///tmp/genie/archives/
      attachments: file:///tmp/genie/attachments/
      jobs: file:///tmp/genie/jobs/
    max:
      stdOutSize: 8589934592
      stdErrSize: 8589934592
    memory:
      maxSystemMemory: 30720
      defaultJobMemory: 1024
      maxJobMemory: 10240
    users:
      creationEnabled: false
      runAsUserEnabled: false
  leader:
    enabled: false
  mail:
    fromAddress: no-reply-genie@geniehost.com
    #user:
    #password:
  redis:
    enabled: false
  retry:
    s3:
      noOfRetries: 5
  security:
    oauth2:
      enabled: false
      pingfederate:
        enabled: false
        jwt:
          enabled: false
    saml:
      enabled: false
    x509:
      enabled: false
  swagger:
    enabled: false
  tasks:
    clusterChecker:
      scheme: http
      port: 8080
      rate: 300000
      lostThreshold: 3
    databaseCleanup:
      enabled: true
      expression: 0 0 0 * * *
      retention: 90
    diskCleanup:
      enabled: true
      expression: 0 0 0 * * *
      retention: 3
    executor:
      pool:
        size: 1
    scheduler:
      pool:
        size: 1

info:
  genie:
    version: GENIE_VERSION

management:
  context-path: /actuator
  security:
    enabled: false

multipart:
  max-file-size: 100MB
  max-request-size: 200MB

security:
  basic:
    enabled: false

spring:
  application:
    name: genie
  cloud:
    cluster:
      leader:
        enabled: false
      zookeeper:
        namespace: /genie/leader/
  jackson:
    date-format: com.netflix.genie.common.util.GenieDateFormat
    time-zone: UTC
  profiles:
    active: dev
  mail:
    #host: localhost
    #testConnection: true
  velocity:
    enabled: false
