##
#
#  Copyright 2015 Netflix, Inc.
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#
##

genie:
  data:
    service:
      retry:
        noOfRetries: 2
        initialInterval: 10
        maxInterval: 10
  health:
    maxCpuLoadPercent: 100
  jobs:
    clusters:
      load-balancers:
        script:
          enabled: true
    locations:
      archives: /archive/location
      jobs: file:///tmp/genie/jobs/

spring:
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
    - net.devh.springboot.autoconfigure.grpc.server.GrpcServerAutoConfiguration
